simpsons/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :characters
  
end

simpsons/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

simpsons/app/models/character.rb
class Character < ApplicationRecord

end

simpsons/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

simpsons/app/controllers/characters_controller.rb
class CharactersController < ApplicationController

	def index
		@characters = Character.all
	end

	def show
		@character = Character.find(params[:id])
	end

	def edit
		@character = Character.find(params[:id])
	end

	def update
		@character = Character.find(params[:id])
		@character.update(character_params)
		redirect_to @character
	end

	def new
		@character = Character.new
	end

	def create
		@character = Character.new(character_params)
		@character.save
		redirect_to @character
	end

	def destroy
		@character = Character.find(params[:id])
		@character.destroy
		redirect_to characters_path
	end

	private
    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :age, :voice_actor, :first_appearance, :job)
    end

end

simpsons/app/helpers/application_helper.rb
module ApplicationHelper
end

simpsons/app/views/characters/edit.html.erb
<h1>EDIT</h1>

<%= form_with(model: @character) do |form| %>

	<div class="field">
		<%= form.label :name %>
		<%= form.text_field :name, id: :character_name %>	
	</div>

	<div>
		<%= form.label :age %>
		<%= form.number_field :age, id: :character_age %>
	</div>

	<div class="field">
		<%= form.label :job %>
		<%= form.text_field :job, id: :character_job %>
	</div>

	<div class="field">
		<%= form.label :voice_actor %>
		<%= form.text_field :voice_actor, id: :character_name %>
	</div>

	<div class="field">
		<%= form.label :first_appearance %>
		<%= form.date_select :first_appearance, start_year:1989, id: :character_first_appearance %>
	</div>

	<div class="field">
		<%=form.submit %>
	</div>


<% end %>

simpsons/app/views/characters/index.html.erb
<h1>Simpsons Characters</h1>

<ul>
    <% @characters.each do |character| %>
        <li>
            <h2><%= character.name %></h2>
            <p><%= character.job %></p>        
            <p><%= character.voice_actor %></p>        
        </li>
    <% end %>
</ul>

<%= link_to 'New Character', new_character_path %>

simpsons/app/views/characters/new.html.erb
<h1>New Characters</h1>

<%= form_with(model: @character) do |form| %>

	<div class="field">
		<%= form.label :name %>
		<%= form.text_field :name, id: :character_name %>	
	</div>

	<div>
		<%= form.label :age %>
		<%= form.number_field :age, id: :character_age %>
	</div>

	<div class="field">
		<%= form.label :job %>
		<%= form.text_field :job, id: :character_job %>
	</div>

	<div class="field">
		<%= form.label :voice_actor %>
		<%= form.text_field :voice_actor, id: :character_name %>
	</div>

	<div class="field">
		<%= form.label :first_appearance %>
		<%= form.date_select :first_appearance, start_year:1989, id: :character_first_appearance %>
	</div>

	<div class="field">
		<%=form.submit %>
	</div>
	

	


<% end %>

simpsons/app/views/characters/show.html.erb
<h1>Show</h1>

<h2><%= @character.name %></h2>
<p><%= @character.job %></p>
<p><%= @character.voice_actor %></p>
<p><%= @character.age %></p>
<p><%= @character.first_appearance %></p>

<%= link_to 'Destroy', @character, method: :delete %>
<%= link_to 'Edit', edit_character_path(@character) %>

simpsons/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpsons</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>